### PR TITLE
deps: qs@6.12.3

### PR DESCRIPTION
**Pull request by melikhov-dev**
Hi! v6.11.1 and v6.11.2 has some fixes:

[Fix] parse: Fix parsing when the global Object prototype is frozen 
[Fix] stringify: encode comma values more consistently

https://github.com/ljharb/qs/blob/main/CHANGELOG.md#6112

### CODE REVIEW

**Comment by wesleytodd** [comment]
Hey @melikhov-dev, thanks for the PR. Any reason not to just jump to `6.12.1`?

**Comment by melikhov-dev** [comment]
Hi, @wesleytodd. Just afraid of any new bugs in minor version :) Take a look at this fix last week https://github.com/ljharb/qs/pull/501

**Comment by wesleytodd** [comment]
@ljharb any risk you can see with us pulling in the latest and pushing a release including this sometime this week?

**Comment by ljharb** [comment]
No; I'd also suggest using `^` since no npm that still can install from the registry is unaware of the carat.

@melikhov-dev bugs happen in all software occasionally; that's what `overrides` is for :-)

**Comment by melikhov-dev** [comment]
@ljharb from my point of view, `^` is better, but I see that all the deps in this package have a fixed or  `~` version

**Comment by melikhov-dev** [comment]
@wesleytodd ok, i did it

**Comment by wesleytodd** [comment]
Ah this error has been happening in all these old CI setups. It isn't because of this PR's changes but because nyc broke in node 8/9. I have a few things I am doing today, but will try to find time to get the CI fixed on this before we merge. Ideally we can get this into the next planned `express` release we are looking to do this week.

**Comment by wesleytodd** [comment]
CI is almost fixed in #523 and then we can merge this. Just wanted to update on it.

**Comment by melikhov-dev** [comment]
Hi, @wesleytodd! 
I see that #523 is merged. Can we retry the tests?

**Comment by wesleytodd** [comment]
Looks like the tests pass. One thing which *used* to be part of the process of merging things was to update the "unreleased" changes in the `HISTORY.md`. I realized recently that I had merged a few things without doing that because of time constraints but I would like to either automate it or get back in the habbit of adding it before merging myself or asking PRs to add it. Since you are active and responsive, [here is an example of this](https://github.com/expressjs/body-parser/pull/448/files#diff-648afe3d986261d8f2015b2b131b0e4a448d4dc6946cfde1a7a836876cee255e), would you mind adding it before I merge?

**Comment by melikhov-dev** [comment]
@wesleytodd ok, I added `unreleased` to `HISTORY.md` and updated `qs` to the latest patch version.

**Comment by wesleytodd** [comment]
This failure is being investigated by folks on the node and npm sides: https://github.com/npm/cli/issues/7657

There is a slack thread in the OpenJS Slack. I am pretty sure we could merge this without issue but I would like to see if we can get a clean CI run.

**Comment by wesleytodd** [comment]
Well now my pin back PR is stuck. So I guess we will just wait on this until github resolves the issue. If it is resolved soon and we can merge that I will merge this. If not, guess we just wait till tomorrow or the node patch goes out.

**Pull request merged**
