### PR TITLE
Also use the qs module for the simple parser

### PR DESCRIPTION
**Pull request by papandreou**
Following up from https://github.com/expressjs/body-parser/pull/326

### CODE REVIEW

**Comment by wesleytodd** [comment]
We are preparing to release 2.0, and to reduce churn and help us I retargeted this to that branch. Would you be able to rebase this so I can merge it there?

**Comment by papandreou** [comment]
@wesleytodd, absolutely! Done.

**Comment by wesleytodd** [comment]
Before I merge this, @ljharb mind taking a quick look to make sure this is good to land for v5? It appears your last comment was in 2020 just mentioning to update, which we will for sure ensure we are before publishing.

**Comment by ljharb** [comment]
still LGTM!

**Pull request merged**
